###
# Archivo: 01_category.http
# Requiere: No hay requisitos previos para acceder a los endpoints de categoría.
###

### Crear Categoría
# @name createCategory
POST http://localhost:3000/categories
Content-Type: application/json

{
    "name": "cafe",
    "description": "Categoría de café"
}
###

@categoryId = {{createCategory.response.body._id}}
### Crear Subcategoría
# @name createSubcategory
POST http://localhost:3000/categories/
Content-Type: application/json

{
    "name": "torrado",
    "parent_id": "{{categoryId}}"
}
###

@categorySlug = {{createSubcategory.response.body.slug}}

### Listar Categorías
GET http://localhost:3000/categories

### Obtener Categoría por slug
# Muestra la categoría asociada al slug y sus categorías padre.
GET http://localhost:3000/categories/{{categorySlug}}

### Actualizar Categoría
PUT http://localhost:3000/categories/{{categoryId}}
Content-Type: application/json

{
    "name": "cafe-updated",
    "description": "Categoría de café actualizada"
}

### Eliminar Categoría
DELETE http://localhost:3000/categories/{{categoryId}}
