###
# Archivo: 04_form.http
# Requiere: No hay requisitos previos para acceder a los endpoints de form
###

### Crear formulario
# @name createForm
POST http://localhost:3000/api/forms
Content-Type: application/json

{
    "name": "Lautaro Becerra",
    "message": "Me interesa el café de la marca Nescafe",
    "phone": "123456789",
    "mail": "lautaro.becerra@example.com"
}
###
@formId = {{createForm.response.body._id}}

### Obtener todos los formularios
GET http://localhost:3000/api/forms
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MDU1NzFjYTJlZWZkNGY2OTM2ZDhkYiIsImVtYWlsIjoiam9hcXVpbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2MTk1ODgzNywiZXhwIjoxNzYxOTU5NzM3fQ.VA5_GWnvKKs5D_zUz_mx-3GMLi7CfrvlocQKNbtlvzc


### Obtener formulario por ID
GET http://localhost:3000/api/forms/{{formId}}
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MDU1NzFjYTJlZWZkNGY2OTM2ZDhkYiIsImVtYWlsIjoiam9hcXVpbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2MTk1ODgzNywiZXhwIjoxNzYxOTU5NzM3fQ.VA5_GWnvKKs5D_zUz_mx-3GMLi7CfrvlocQKNbtlvzc



### Actualizar formulario
PUT http://localhost:3000/api/forms/{{formId}}
Content-Type: application/json

{
    "name": "Joaquín Castellano",
    "message": "Me interesa comprar una cafetera",
    "phone": "987654321",
    "mail": "joaquincastellano350@gmail.com"
}

### Eliminar formulario
DELETE http://localhost:3000/api/forms/{{formId}}
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MDU1NzFjYTJlZWZkNGY2OTM2ZDhkYiIsImVtYWlsIjoiam9hcXVpbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2MTk1ODgzNywiZXhwIjoxNzYxOTU5NzM3fQ.VA5_GWnvKKs5D_zUz_mx-3GMLi7CfrvlocQKNbtlvzc

