### Agregar a la lista de deseos
POST http://localhost:3000/api/wishlist/6908d84a5f1052b193bf0260
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MDhjYzMxYTljNTUxYWQ0MTY5ZmM0MiIsImVtYWlsIjoiam9hcXVpbkBwcnVlYmEuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NjIxODgxNjMsImV4cCI6MTc2MjE4OTA2M30.H_GXqnrnoO3sQKJ6zjmQ1PKmE_v9ktjDzFy9r0rOn0k

### Obtener lista de deseos
GET http://localhost:3000/api/wishlist
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MDhjYzMxYTljNTUxYWQ0MTY5ZmM0MiIsImVtYWlsIjoiam9hcXVpbkBwcnVlYmEuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NjIxODgxNjMsImV4cCI6MTc2MjE4OTA2M30.H_GXqnrnoO3sQKJ6zjmQ1PKmE_v9ktjDzFy9r0rOn0k

### Eliminar de la lista de deseos
DELETE http://localhost:3000/api/wishlist/6908d84a5f1052b193bf0260
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MDhjYzMxYTljNTUxYWQ0MTY5ZmM0MiIsImVtYWlsIjoiam9hcXVpbkBwcnVlYmEuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NjIxODgxNjMsImV4cCI6MTc2MjE4OTA2M30.H_GXqnrnoO3sQKJ6zjmQ1PKmE_v9ktjDzFy9r0rOn0k

### Fusionar lista de deseos (cliente anónimo al iniciar sesión)
POST http://localhost:3000/api/wishlist/merge
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MDhjYzMxYTljNTUxYWQ0MTY5ZmM0MiIsImVtYWlsIjoiam9hcXVpbkBwcnVlYmEuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NjIxODgxNjMsImV4cCI6MTc2MjE4OTA2M30.H_GXqnrnoO3sQKJ6zjmQ1PKmE_v9ktjDzFy9r0rOn0k

{
    "productsIds": ["6908d8575f1052b193bf0263", "6908d8635f1052b193bf0266"]
}

#this.router.use(requireAuth);
#this.router.get("/", wishlistController.getWishlist);
#this.router.post("/:productId", wishlistController.addToWishlist);
#this.router.delete("/:productId", wishlistController.removeFromWishlist);
#this.router.post("/merge", validate(ProductsSchema), wishlistController.mergeWishlist);

